### ISSUE TITLE
client side usage

### ISSUE THREAD

**Issue by pirxpilot** [darkskyapp/tz-lookup#10]
I am experimenting with using tz-lookup on the client. Feel free to close this issue if this is something that you are not interested in or have a different vision for.

I have a [working version][demo] implemented in [browser-friendly] branch of my fork

Some things to consider:
- node's `Buffer` replacement  - `ArrayBuffer`, typed Arrays and `DataView` - nothing controversial here I hope  
- need to move `tz.bin` to client - I chose to do that by providing tz.bin configuration in HTML dataset and then using `fetch` to actually download the data... - there are other ways to do that, I chose this one since it's compatible with using cachify, service workers and CDNs
- initialization - which involves downloading and converting (byte order!) `tz.bin` - has to be asynchronous on the client (or so I think) - to make things easier I changed the server init to be async as well. That makes it easy for browserify to use a different init module on the client, but it makes things more  complicated on the server. Maybe we should have an optional sync init as well?
- rolled back some ES6 (`const` and `let`) changes - since I didn't think it's worth transpiling just for that, but it's simple to revert

In any case - if you're interested please have a look at my branch and let me know what you think.

[demo]: https://pirxpilot.github.io/tz-lookup/
[browser-friendly]: https://github.com/pirxpilot/tz-lookup/tree/browser-friendly

**Comment by ironwallaby** [comment]
Wow, you're a brave person! I'd never even considered the possibility of running this in a browser, but it's actually a really good use-case—the compact data file is a really big deal there, and the simplicity of implementation keeps overhead low.

Gimme a little bit to dig into your implementation and follow what's going on, but I really like the idea of supporting both environments.

If other people are looking at the code, I should probably write up some comments too, huh?

**Comment by ironwallaby** [comment]
So I like this, but the issue that I have with it is the method of loading the data file (`tz.bin`)—having to reference it separately is a poor developer experience, and also splits the library between `sync` and `async` versions, which is something I'd like to avoid.

So... I went and rewrote how I generate up the library, so that the data is packed into the library itself, meaning you don't need to load any external dependencies. 😄 I managed the pack the data such that it takes up the same amount of space, even though it's stored as ASCII text (and not binary data), so we're left with simply having fewer network requests (which should keep things fast).

I have a branch showcasing it here: https://github.com/darkskyapp/tz-lookup/blob/client/test.html

Does that solution work for you?

**Comment by pirxpilot** [comment]
Nice! Really like the idea of encoding tz.bin as ASCII, which solves the separate download issue. I fully agree that not having an async init is a huge win for majority of the users.

BTW: did you try to encode it using 90 consecutive characters - that would allow for using `String.charCodeAt(n)`  instead of calling `indexOf` in the decoding loop. I might try and see how that works.

I am not sure if having the code wrapped in IIFE makes things easier for anyone. Most folks use browserify, webpack, or rollup anyway to build client modules. I'd just put the TZ data in a module, require it normally and let the build tools handle it for the client version. Checking for `require` def. does not work for browserify since it defines require on the client.

I'll probably stick to my implementation for Furkot for a while: having an extra network request does not bother us since majority of our users are on HTTP2 enabled browsers. We can get tz.bin a separate, cachified  URL with long expiration - since it rarely changes folks will only download it once anyway. And finally, we can delay the download till we actually start messing with timezones ;-)
That said I realize this is a peculiar set of requirements...

Thanks for the great library!

[Furkot]: https://trips.furkot.com

**Comment by ironwallaby** [comment]
Regarding 90 consecutive characters: I didn't even attempt it, due to the need to escape `"` and `\`. But now that you mention it, there's a range of 56 ASCII characters that avoids these (`#` through `[`), and that's more than enough to pack this data without a space penalty. I'll rebuild the data and give it a try, it should be an easy win.

Regarding IIFE: interesting—I thought this was still best-practice if you used strict mode! But now that I think of it, everything is local to the `tzlookup` function, so I can just put strict mode in there.

Regarding the `require` check: no problem, I'll just have the library check if `tzlookup` is defined globally and, if not, attempt to require it.

I'll have these change made in a little bit and will note when the branch is updated.

**Comment by ironwallaby** [comment]
The above changes have been made. (No issues on repacking or reordering anything.) It's been a _long_ time since I've worked on the web, though, so I'd appreciate an eye on whether my changes fix the concerns you noted!

**Comment by ironwallaby** [comment]
I've merged in #11 and cut a new release for this. Please open another issue if you have specific comments on what I've done!
