### ISSUE TITLE
Lookup historical timezones

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/tz-lookup#19]
Timezone mapping is a political designation, and therefore changes over time. We've occasionally received requests for being able to lookup timezones in the past, and this would be an interesting technical challenge.

There are two components to it, I believe:

1. Changing the 2D quadtree storage format into a 3D octree storage format. This is not complicated.
2. Obtaining historical mappings of timezones. Presumably, we'd want a series of 2D maps, each of which corresponds to the timeslice at each timezone data change.

At lookup, we'd find the X (longitude: linear mapping from degrees), Y (latitude: linear mapping from degrees), and Z (time: binary search of data array corresponding to the data from [2]) coordinates of the data we want, and then simply traverse the octree similarly to how we presently traverse the quadtree.

The data file would become larger, but not horribly so; most timezones haven't changed too much over time, so the octree should compress things very well. At worst, we can move back to static binary data, gzip it, and gunzip it again at runtime.

So, this is all straightforward except obtaining the raw source data. Is that available anywhere?

**Comment by evansiroky** [comment]
Good luck finding historical data.  :)

I'm curious though, what would be a use case that wouldn't already be covered by the historical record of time changes that come with a tzdb identifier?

**Comment by ironwallaby** [comment]
In general, any change of political leadership tends to create a change in TZID.

One recent example is [Sevastopol](https://en.wikipedia.org/wiki/Sevastopol). Presently, it is (_de facto_) under MSK (Moscow Time), but just a few years ago was under EET (Eastern European Time).

**Comment by evansiroky** [comment]
That particular area seems to be covered with [this rule in the timzone db](https://github.com/eggert/tz/blob/master/europe#L2633-L2667).

**Comment by ironwallaby** [comment]
That's interesting. Does this mean that whenever a new political event happens (e.g. a state splitting or being taken over or whatever), a new TZID is created to handle the difference? (That is, new TZIDs come into existence, but old ones never disappear?)

**Comment by evansiroky** [comment]
I believe so, at least it has been this way since I've been working on timezone-boundary-builder.  As long as you're not going further back than 1970 (which the tzdb notes its lack of reliable data in some cases) maybe you'd be fine.  

However, I'm pretty sure that an event such as when [Norway almost gifted a mountain to Finland](http://www.independent.co.uk/news/world/europe/norway-finland-mount-halti-mountain-centenary-independence-erna-solberg-a7364136.html) would not warrant a change in the tzdb, but would probably show up in timezone-boundary-builder as the borders would get moved.  Therefore, something like that could cause a use case where this issue would apply.  Although I wonder how many people visit that part of the world in comparison to Antarctica which is currently completely missing from timezone-boundary-builder.  I always wonder what to do about Antarctica in my project.  I've heard all researchers there use New Zealand time now and a number of outposts have been abandoned.  Do those abandoned areas still use the local time they once did... or are they now New Zealand time?  I don't know who to ask.

**Comment by ironwallaby** [comment]
If that's the case, then this issue is a nonissue and we can close it. Which is kinda nice.

In the case of minor border shifts (e.g. Norway giving a peak to Finland, or [India and Bangladesh swapping enclaves and exclaves](https://en.wikipedia.org/wiki/India–Bangladesh_enclaves) to simplify their borders, or whatever), I think we can safely ignore them. This library doesn't strive for perfection, and instead just tries to cover common cases. (This allows us to use lossy compression in unpopulated areas, making the database manageable.) We'd simply fix cases like as one-off exceptions as they come up.

As for Antarctica, that one's very difficult and I don't have a good answer. As for my part, I'm inclined to consider Antartica similar to international waters: there are no formally defined timezones, and it's up to the ship's captain (or the commander of a particular base) to define what timezone they use, but it doesn't map to geography so much as to the people operating on the base. (That said, if somebody complained about it, we'd probably fix it as a one-off anyway.)

I'm going to leave this issue open until I find an authoritative source stating that IANA timezones are intended to function independently of time. Once a source is found, the README for this library should get updated with that information.

**Comment by evansiroky** [comment]
Sounds good on all accounts.  I've thought about adding ETC/## zones to timezone-boundary-builder for everywhere where there wasn't a zone.

**Comment by ironwallaby** [comment]
Closing this as it does not appear to be relevant (e.g. it is solved by using the timezone-to-offset conversion downstream of us, not the location-to-timezone conversion that this library performs).
