### ISSUE TITLE
Mexico's Southeast Zone (Quintana Roo) should be eastern standard time

### ISSUE THREAD

**Issue by lianga888** [darkskyapp/tz-lookup#40]
There are some issues with the timezone returned for Mexico's Southeast Zone. The entire region should be EST, but I'm seeing that with the exception of a small radius around Cancun, that we're returning Central time for the region

**Comment by ironwallaby** [comment]
Most likely the issue is that the entire state (with the exception of Cancún) is being considered rural, and therefore the compression isn't recursing down as far as it should.

I think the easiest way to fix this in practice is to add forced urban hacks for every significant town in the region. https://en.wikipedia.org/wiki/Municipalities_of_Quintana_Roo

Happy to take this on myself or show you how to do it, if you like.

**Comment by ironwallaby** [comment]
I went ahead and did this since I was already in the repo for other reasons. Here's what I did, for posterity:

1. I followed that Wikipedia page and grabbed the location of every municipal seat in the state.
2. I added them all to the tests, at the end of the "hand-crafted" section.
3. I ran the tests. Most of those locations worked fine! Only two failed: José María Morelos and Kantunilkín.
4. I added the locations for those two locations to `pack.js`, under the "HACK: Add custom areas" header.
5. I ran `rebuild.sh` to regenerate the data, verified that the tests passed, and merged.

Detailed diff outlining all this is here: https://github.com/darkskyapp/tz-lookup/commit/0881514b216da214e33cbaafdebcc08ea799c23b
